# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4327bdabb95e87cdff2dc526d99d8c9b8091c86544358d8f1c171b4537b3d6c91b0ff81976bd5e125ac66dd6073e4309eca288e5122e68a87429b91715af6bbb

test:
  secret_key_base: 71fa2a027432b11abcaf6364158eb1276cb4bff9f2ef4134bf7324d207f367abfdca4219a24897314a699ca0077e1f5565f924794427a8e54d1945d1fc3dd009

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
